// Test.cpp : 定义控制台应用程序的入口点。
//

#include "stdafx.h"
#include "../ZG/RTS.h"

int main()
{
	_CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);
	LPZGTILEMANAGER pManager0;
	pManager0 = ZGRTSCreateManager(1024, 10, 10, 1);
	LPZGTILEOBJECTACTION pAction0;
	pAction0 = ZGRTSCreateAction(1, 0, 1);
	ZGRTSSetEvaluationToAction(pAction0, 10);
	ZGRTSSetMinEvaluationToAction(pAction0, 10);
	ZGRTSSetMaxEvaluationToAction(pAction0, 100);
	ZGRTSSetMaxDistanceToAction(pAction0, 100);
	ZGRTSSetMaxDepthToAction(pAction0, 100);
	ZGRTSSetChildToAction(pAction0, pAction0, 0);
	LPZGTILEMANAGEROBJECT pObject0;
	pObject0 = ZGRTSCreateObject(1, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject0, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject0, 5, 100);
	ZGRTSSetAttributeToObjectUINT(pObject0, 2, 1000);
	ZGRTSSetAttributeToObjectUINT(pObject0, 3, 1500);
	ZGRTSSetDistanceToObject(pObject0, 10);
	ZGRTSSetRangeToObject(pObject0, 10);
	ZGRTSSetActionToObject(pObject0, pAction0);
	ZGRTSSetAttributeToObjectUINT(pObject0, 6, 0);
	ZGRTSSetAttributeToObjectUINT(pObject0, 7, 0);
	ZGRTSSetAttributeToObjectUINT(pObject0, 8, 0);
	ZGRTSSetAttributeToObjectUINT(pObject0, 9, 0);
	ZGRTSSetObjectToManager(pObject0, pManager0, 84);
	ZGRTSAddObjectToManager(pObject0, pManager0);
	LPZGTILEOBJECTACTION pAction1;
	pAction1 = ZGRTSCreateAction(1, 0, 1);
	ZGRTSSetEvaluationToAction(pAction1, 10);
	ZGRTSSetMinEvaluationToAction(pAction1, 10);
	ZGRTSSetMaxEvaluationToAction(pAction1, 100);
	ZGRTSSetMaxDistanceToAction(pAction1, 100);
	ZGRTSSetMaxDepthToAction(pAction1, 100);
	ZGRTSSetChildToAction(pAction1, pAction1, 0);
	LPZGTILEMANAGEROBJECT pObject1;
	pObject1 = ZGRTSCreateObject(1, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject1, 1, 1);
	ZGRTSSetAttributeToObjectUINT(pObject1, 5, 100);
	ZGRTSSetAttributeToObjectUINT(pObject1, 2, 1000);
	ZGRTSSetAttributeToObjectUINT(pObject1, 3, 1500);
	ZGRTSSetDistanceToObject(pObject1, 10);
	ZGRTSSetRangeToObject(pObject1, 10);
	ZGRTSSetActionToObject(pObject1, pAction1);
	ZGRTSSetAttributeToObjectUINT(pObject1, 6, 0);
	ZGRTSSetAttributeToObjectUINT(pObject1, 7, 0);
	ZGRTSSetAttributeToObjectUINT(pObject1, 8, 0);
	ZGRTSSetAttributeToObjectUINT(pObject1, 9, 0);
	ZGRTSSetObjectToManager(pObject1, pManager0, 17);
	ZGRTSAddObjectToManager(pObject1, pManager0);
	LPZGTILEOBJECTACTION pAction2;
	pAction2 = ZGRTSCreateAction(1, 0, 1);
	ZGRTSSetEvaluationToAction(pAction2, 10);
	ZGRTSSetMinEvaluationToAction(pAction2, 10);
	ZGRTSSetMaxEvaluationToAction(pAction2, 100);
	ZGRTSSetMaxDistanceToAction(pAction2, 100);
	ZGRTSSetMaxDepthToAction(pAction2, 100);
	ZGRTSSetChildToAction(pAction2, pAction2, 0);
	LPZGTILEMANAGEROBJECT pObject2;
	pObject2 = ZGRTSCreateObject(1, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject2, 1, 1);
	ZGRTSSetAttributeToObjectUINT(pObject2, 5, 100);
	ZGRTSSetAttributeToObjectUINT(pObject2, 2, 1000);
	ZGRTSSetAttributeToObjectUINT(pObject2, 3, 1500);
	ZGRTSSetDistanceToObject(pObject2, 10);
	ZGRTSSetRangeToObject(pObject2, 10);
	ZGRTSSetActionToObject(pObject2, pAction2);
	ZGRTSSetAttributeToObjectUINT(pObject2, 6, 0);
	ZGRTSSetAttributeToObjectUINT(pObject2, 7, 0);
	ZGRTSSetAttributeToObjectUINT(pObject2, 8, 0);
	ZGRTSSetAttributeToObjectUINT(pObject2, 9, 0);
	ZGRTSSetObjectToManager(pObject2, pManager0, 21);
	ZGRTSAddObjectToManager(pObject2, pManager0);
	LPZGTILEOBJECTACTION pAction3;
	pAction3 = ZGRTSCreateAction(1, 0, 1);
	ZGRTSSetEvaluationToAction(pAction3, 10);
	ZGRTSSetMinEvaluationToAction(pAction3, 10);
	ZGRTSSetMaxEvaluationToAction(pAction3, 100);
	ZGRTSSetMaxDistanceToAction(pAction3, 100);
	ZGRTSSetMaxDepthToAction(pAction3, 100);
	ZGRTSSetChildToAction(pAction3, pAction3, 0);
	LPZGTILEMANAGEROBJECT pObject3;
	pObject3 = ZGRTSCreateObject(1, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject3, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject3, 5, 100);
	ZGRTSSetAttributeToObjectUINT(pObject3, 2, 1000);
	ZGRTSSetAttributeToObjectUINT(pObject3, 3, 1500);
	ZGRTSSetDistanceToObject(pObject3, 10);
	ZGRTSSetRangeToObject(pObject3, 10);
	ZGRTSSetActionToObject(pObject3, pAction3);
	ZGRTSSetAttributeToObjectUINT(pObject3, 6, 0);
	ZGRTSSetAttributeToObjectUINT(pObject3, 7, 0);
	ZGRTSSetAttributeToObjectUINT(pObject3, 8, 0);
	ZGRTSSetAttributeToObjectUINT(pObject3, 9, 0);
	ZGRTSSetObjectToManager(pObject3, pManager0, 48);
	ZGRTSAddObjectToManager(pObject3, pManager0);
	LPZGTILEOBJECTACTION pAction4;
	pAction4 = ZGRTSCreateAction(1, 0, 1);
	ZGRTSSetEvaluationToAction(pAction4, 10);
	ZGRTSSetMinEvaluationToAction(pAction4, 10);
	ZGRTSSetMaxEvaluationToAction(pAction4, 100);
	ZGRTSSetMaxDistanceToAction(pAction4, 100);
	ZGRTSSetMaxDepthToAction(pAction4, 100);
	ZGRTSSetChildToAction(pAction4, pAction4, 0);
	LPZGTILEMANAGEROBJECT pObject4;
	pObject4 = ZGRTSCreateObject(1, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject4, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject4, 5, 100);
	ZGRTSSetAttributeToObjectUINT(pObject4, 2, 1000);
	ZGRTSSetAttributeToObjectUINT(pObject4, 3, 1500);
	ZGRTSSetDistanceToObject(pObject4, 10);
	ZGRTSSetRangeToObject(pObject4, 10);
	ZGRTSSetActionToObject(pObject4, pAction4);
	ZGRTSSetAttributeToObjectUINT(pObject4, 6, 0);
	ZGRTSSetAttributeToObjectUINT(pObject4, 7, 0);
	ZGRTSSetAttributeToObjectUINT(pObject4, 8, 0);
	ZGRTSSetAttributeToObjectUINT(pObject4, 9, 0);
	ZGRTSSetObjectToManager(pObject4, pManager0, 98);
	ZGRTSAddObjectToManager(pObject4, pManager0);
	LPZGTILEOBJECTACTION pAction5;
	pAction5 = ZGRTSCreateAction(1, 0, 1);
	ZGRTSSetEvaluationToAction(pAction5, 10);
	ZGRTSSetMinEvaluationToAction(pAction5, 10);
	ZGRTSSetMaxEvaluationToAction(pAction5, 100);
	ZGRTSSetMaxDistanceToAction(pAction5, 100);
	ZGRTSSetMaxDepthToAction(pAction5, 100);
	ZGRTSSetChildToAction(pAction5, pAction5, 0);
	LPZGTILEMANAGEROBJECT pObject5;
	pObject5 = ZGRTSCreateObject(1, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject5, 1, 1);
	ZGRTSSetAttributeToObjectUINT(pObject5, 5, 100);
	ZGRTSSetAttributeToObjectUINT(pObject5, 2, 1000);
	ZGRTSSetAttributeToObjectUINT(pObject5, 3, 1500);
	ZGRTSSetDistanceToObject(pObject5, 10);
	ZGRTSSetRangeToObject(pObject5, 10);
	ZGRTSSetActionToObject(pObject5, pAction5);
	ZGRTSSetAttributeToObjectUINT(pObject5, 6, 0);
	ZGRTSSetAttributeToObjectUINT(pObject5, 7, 0);
	ZGRTSSetAttributeToObjectUINT(pObject5, 8, 0);
	ZGRTSSetAttributeToObjectUINT(pObject5, 9, 0);
	ZGRTSSetObjectToManager(pObject5, pManager0, 61);
	ZGRTSAddObjectToManager(pObject5, pManager0);
	ZGUINT uInfoCount;
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	LPZGTILEOBJECTACTION pAction6;
	pAction6 = ZGRTSCreateAction(1, 0, 1);
	ZGRTSSetEvaluationToAction(pAction6, 10);
	ZGRTSSetMinEvaluationToAction(pAction6, 10);
	ZGRTSSetMaxEvaluationToAction(pAction6, 100);
	ZGRTSSetMaxDistanceToAction(pAction6, 100);
	ZGRTSSetMaxDepthToAction(pAction6, 100);
	ZGRTSSetChildToAction(pAction6, pAction6, 0);
	LPZGTILEMANAGEROBJECT pObject6;
	pObject6 = ZGRTSCreateObject(1, 1, 0);
	ZGRTSSetAttributeToObjectUINT(pObject6, 1, 1);
	ZGRTSSetAttributeToObjectUINT(pObject6, 5, 100);
	ZGRTSSetAttributeToObjectUINT(pObject6, 2, 200);
	ZGRTSSetAttributeToObjectUINT(pObject6, 3, 3);
	ZGRTSSetDistanceToObject(pObject6, 10);
	ZGRTSSetRangeToObject(pObject6, 10);
	ZGRTSSetActionToObject(pObject6, pAction6);
	ZGRTSSetAttributeToObjectUINT(pObject6, 6, 2);
	ZGRTSSetAttributeToObjectUINT(pObject6, 7, 2);
	ZGRTSSetAttributeToObjectUINT(pObject6, 8, 0);
	ZGRTSSetAttributeToObjectUINT(pObject6, 9, 0);
	ZGRTSSetObjectToManager(pObject6, pManager0, 75);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	ZGRTSRun(pManager0, 300, &uInfoCount);
	LPZGRTSINFO pInfos;
	ZGRTSDo(pManager0, pObject6, 85, 6212, &uInfoCount, &pInfos);

    return _CrtDumpMemoryLeaks();
}

